### ISSUE TITLE
Compiler OS go packages

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/go-feedstock#28]
Appears there are builds of the compiler OS go packages for OSes they shouldn't be used on. For example, `go_linux-64` is not only available on Linux, but also on macOS and Windows. This is also true of `go_osx-64` and `go_win-64`. In fact there are no Windows builds of `go_win-64`.

**Comment by nehaljwani** [comment]
Go generates static binaries and is capable of doing so cross-platform. On Linux, I can do:
```
# Install the cross-compiler
$ conda install -y go_win-64

# Hello world!
$ cat <<EOF > hw.go
package main

import "fmt"

func main() {
    fmt.Printf("Hello, World!\n")
}
EOF

# Re-check target platform
$ env | grep -i GOOS=
GOOS=windows

# Build the exe
$ go build hw.go

# What did I build?
$ file hw.exe
hw.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by nehaljwani** [comment]
I can run it too ;-)
```
$ wine64 hw.exe
hello world
```

**Comment by jakirkham** [comment]
I see. So they are for cross-compilation?

**Comment by nehaljwani** [comment]
Indeed.

**Comment by nehaljwani** [comment]
Windows CI run still failing :(
```
[WARNING] Token warning: expires in 25 days
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 131, in <module>
    main()
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 121, in main
    upload(cli, fname, owner, channel)
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 68, in upload
    env=os.environ)
  File "C:\Miniconda36-x64\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Miniconda36-x64\Scripts\upload_or_check_non_existence.py", line 27, in get_temp_token
    shutil.rmtree(dn)
  File "C:\Miniconda36-x64\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniconda36-x64\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Miniconda36-x64\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpwkslut82\\binstar.token'
```

**Comment by jakirkham** [comment]
Known issue ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/14 ). We have had a hard time fixing it. If you would like to take a look, we would certainly appreciate the help. Interestingly it does not block uploading.

**Comment by sodre** [comment]
I deprecated the cross compiler go packages. If we need this again lets open an issue.
