### ISSUE TITLE
Missing  go-cgo_linux-ppc64le package and likely go-cgo_linux-aarch64

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/go-feedstock#97]
In trying to build: https://github.com/conda-forge/zaber-motion-feedstock/pull/29

it became obvious that there was a challenge to build the package for the ppc64le and aarch64.

I used mamba to try to build the recipe and the error provided is:

```
(base) [hmaarrfk@conda-forge zaber-motion-feedstock]$ mamba build -m .ci_support/linux_ppc64le_python3.8.____cpython.yaml recipe/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/hmaarrfk/git/zaber-motion-feedstock/.ci_support/linux_ppc64le_python3.8.____cpython.yaml
INFO:conda_build.variants:Adding in variants from /home/hmaarrfk/git/zaber-motion-feedstock/.ci_support/linux_ppc64le_python3.8.____cpython.yaml
Attempting to finalize metadata for zaber-motion
INFO:conda_build.metadata:Attempting to finalize metadata for zaber-motion
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/hmaarrfk/mambaforge/conda-bld/work 
  Test:
 /home/hmaarrfk/mambaforge/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/hmaarrfk/mambaforge/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho 
  Build:
source activate  /home/hmaarrfk/mambaforge/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda_build/environ.py", line 802, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/core/solve.py", line 565, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/hmaarrfk/mambaforge/lib/python3.8/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - gcc_linux-ppc64le=9
  - gxx_linux-ppc64le=9
  - go-cgo_linux-ppc64le

```

**Comment by hmaarrfk** [comment]
Opps, i think i selected the wrong arch. Will open again when mamba finished finding the error.
